# Grafana Data Source Provisioning - Prometheus
# Automatically configures Prometheus as a data source on Grafana startup

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
      queryTimeout: 60s
      customQueryParameters: ''
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      incrementalQuerying: false
      incrementalQueryOverlapWindow: 10m
    version: 1
